"""
aurelius.api.main
=================
FastAPI application entry point.

This module creates the FastAPI application instance, registers middleware,
configures exception handlers, and mounts API routers.

Milestone 0: Only the /api/v1/health endpoint is implemented.
             No market data, no provider calls, no database access.

Milestone 1: Will add:
  - /api/v1/market/quote/{ticker}
  - /api/v1/market/ohlcv/{ticker}
  - Provider dependency injection

Running the server (development):
  cd backend
  uvicorn aurelius.api.main:app --reload --port 8000

API documentation (auto-generated by FastAPI):
  http://localhost:8000/docs     (Swagger UI)
  http://localhost:8000/redoc   (ReDoc)
  http://localhost:8000/openapi.json
"""

import logging

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

from aurelius import __version__
from aurelius.domain.errors import (
    AureliusError,
    CalculationError,
    DataNotFoundError,
    DataQualityError,
    InvalidSearchQueryError,
    InvalidTickerError,
    ProviderRateLimitError,
    ProviderUnavailableError,
)
from aurelius.infrastructure.logging import configure_logging
from aurelius.settings import get_settings

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Application factory
# ---------------------------------------------------------------------------


def create_app() -> FastAPI:
    """
    Create and configure the FastAPI application.

    Using a factory function (rather than a module-level `app = FastAPI()`)
    enables clean test isolation: tests can call create_app() with different
    settings without shared state bleeding between tests.
    """
    settings = get_settings()
    configure_logging(settings.aurelius_log_level)

    app = FastAPI(
        title="AURELIUS API",
        description=(
            "AURELIUS — Financial Intelligence & Research Terminal. "
            "Backend API providing market data, financial analytics, "
            "and quantitative research capabilities."
        ),
        version=__version__,
        # OpenAPI JSON served at /openapi.json; disable in production if needed.
        openapi_url="/openapi.json",
        docs_url="/docs",
        redoc_url="/redoc",
    )

    # -----------------------------------------------------------------------
    # CORS middleware
    # -----------------------------------------------------------------------
    # Allow the frontend dev server to call the API in development.
    # In production, replace with the actual deployed frontend origin.
    # Never use allow_origins=["*"] with allow_credentials=True.
    app.add_middleware(
        CORSMiddleware,
        allow_origins=settings.cors_origins,
        allow_credentials=False,  # No session cookies in this architecture
        allow_methods=["GET", "POST"],  # Only methods we actually use
        allow_headers=["Content-Type", "Accept"],
    )

    # -----------------------------------------------------------------------
    # Exception handlers
    # -----------------------------------------------------------------------
    # Map domain exceptions to HTTP responses.
    # This keeps HTTP concerns out of the domain layer.

    @app.exception_handler(InvalidTickerError)
    async def invalid_ticker_handler(
        request: Request, exc: InvalidTickerError
    ) -> JSONResponse:
        return JSONResponse(
            status_code=400,
            content={
                "error": "INVALID_TICKER",
                "message": exc.message,
                "ticker": exc.ticker,
            },
        )

    @app.exception_handler(InvalidSearchQueryError)
    async def invalid_search_query_handler(
        request: Request, exc: InvalidSearchQueryError
    ) -> JSONResponse:
        return JSONResponse(
            status_code=400,
            content={
                "error": "INVALID_SEARCH_QUERY",
                "message": exc.message,
                "query": exc.query,
            },
        )

    @app.exception_handler(DataNotFoundError)
    async def data_not_found_handler(
        request: Request, exc: DataNotFoundError
    ) -> JSONResponse:
        return JSONResponse(
            status_code=404,
            content={
                "error": "DATA_NOT_FOUND",
                "message": exc.message,
                "ticker": exc.ticker,
            },
        )

    @app.exception_handler(ProviderRateLimitError)
    async def rate_limit_handler(
        request: Request, exc: ProviderRateLimitError
    ) -> JSONResponse:
        logger.warning(
            "Provider rate limit hit: provider=%s ticker=%s",
            exc.provider,
            exc.ticker,
        )
        return JSONResponse(
            status_code=429,
            content={
                "error": "PROVIDER_RATE_LIMIT",
                "message": exc.message,
                "provider": exc.provider,
            },
        )

    @app.exception_handler(ProviderUnavailableError)
    async def provider_unavailable_handler(
        request: Request, exc: ProviderUnavailableError
    ) -> JSONResponse:
        logger.error(
            "Provider unavailable: provider=%s ticker=%s message=%s",
            exc.provider,
            exc.ticker,
            exc.message,
        )
        return JSONResponse(
            status_code=503,
            content={
                "error": "PROVIDER_UNAVAILABLE",
                "message": exc.message,
                "provider": exc.provider,
            },
        )

    @app.exception_handler(DataQualityError)
    async def data_quality_handler(
        request: Request, exc: DataQualityError
    ) -> JSONResponse:
        logger.error(
            "Data quality failure: check=%s ticker=%s message=%s",
            exc.check,
            exc.ticker,
            exc.message,
        )
        return JSONResponse(
            status_code=422,
            content={
                "error": "DATA_QUALITY_FAILURE",
                "message": exc.message,
                "check": exc.check,
            },
        )

    @app.exception_handler(CalculationError)
    async def calculation_error_handler(
        request: Request, exc: CalculationError
    ) -> JSONResponse:
        logger.error(
            "Calculation error: formula=%s message=%s",
            exc.formula,
            exc.message,
        )
        return JSONResponse(
            status_code=500,
            content={
                "error": "CALCULATION_ERROR",
                "message": exc.message,
                "formula": exc.formula,
            },
        )

    @app.exception_handler(AureliusError)
    async def generic_aurelius_error_handler(
        request: Request, exc: AureliusError
    ) -> JSONResponse:
        """Catch-all for any AureliusError not handled by a more specific handler."""
        logger.error("Unhandled AureliusError: %s", exc)
        return JSONResponse(
            status_code=500,
            content={
                "error": "INTERNAL_ERROR",
                "message": str(exc),
            },
        )

    # -----------------------------------------------------------------------
    # Routers
    # -----------------------------------------------------------------------
    from aurelius.api.v1.router import router as v1_router  # noqa: PLC0415

    app.include_router(v1_router, prefix="/api/v1")

    logger.info(
        "AURELIUS API started: version=%s env=%s",
        __version__,
        settings.aurelius_env,
    )

    return app


# Module-level app instance for Uvicorn.
# Uvicorn is invoked as: uvicorn aurelius.api.main:app
app = create_app()
