"""
aurelius.domain.fundamental.enums
=================================
Enumerations for fundamental analysis metrics, categories, operational statuses,
and auditable diagnostic codes.
"""

from enum import StrEnum


class MetricCategory(StrEnum):
    """
    Core fundamental analysis analytical categories.
    """

    GROWTH = "GROWTH"
    PROFITABILITY = "PROFITABILITY"
    LIQUIDITY = "LIQUIDITY"
    SOLVENCY = "SOLVENCY"
    EFFICIENCY = "EFFICIENCY"
    CASH_FLOW = "CASH_FLOW"


class MetricStatus(StrEnum):
    """
    Operational status of a derived fundamental metric result.
    VALID: Metric calculated successfully according to canonical methodology.
    UNAVAILABLE: Missing required inputs or insufficient period history.
    NOT_APPLICABLE: Concept not applicable to entity structure (e.g. unclassified balance sheet).
    DISTORTED: Mathematically invalid or economically misleading (e.g. negative equity, zero division).
    """

    VALID = "VALID"
    UNAVAILABLE = "UNAVAILABLE"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    DISTORTED = "DISTORTED"


class DiagnosticCode(StrEnum):
    """
    Standardized machine-readable diagnostic codes for fundamental analysis.
    """

    # Presence & Structure
    MISSING_REQUIRED_FACT = "MISSING_REQUIRED_FACT"
    MISSING_PRIOR_PERIOD = "MISSING_PRIOR_PERIOD"
    INSUFFICIENT_PERIODS_FOR_AVERAGE = "INSUFFICIENT_PERIODS_FOR_AVERAGE"
    INSUFFICIENT_PERIODS_FOR_TTM = "INSUFFICIENT_PERIODS_FOR_TTM"
    INCOMPATIBLE_TTM_QUARTERS = "INCOMPATIBLE_TTM_QUARTERS"
    CONFLICTING_PERIOD_FACTS = "CONFLICTING_PERIOD_FACTS"
    PERIOD_ALIGNMENT_MISMATCH = "PERIOD_ALIGNMENT_MISMATCH"
    UNCLASSIFIED_BALANCE_SHEET = "UNCLASSIFIED_BALANCE_SHEET"
    SHORT_TERM_DEBT_UNAVAILABLE = "SHORT_TERM_DEBT_UNAVAILABLE"
    LONG_TERM_DEBT_UNAVAILABLE = "LONG_TERM_DEBT_UNAVAILABLE"

    # Mathematical & Denominator Semantics
    ZERO_DIVISION = "ZERO_DIVISION"
    NEGATIVE_OR_ZERO_EQUITY = "NEGATIVE_OR_ZERO_EQUITY"
    NEGATIVE_OR_ZERO_EBITDA = "NEGATIVE_OR_ZERO_EBITDA"
    ZERO_OR_NEGATIVE_REVENUE = "ZERO_OR_NEGATIVE_REVENUE"
    NEGATIVE_NET_INCOME = "NEGATIVE_NET_INCOME"
    NEGATIVE_BASE_REVENUE = "NEGATIVE_BASE_REVENUE"
    ZERO_INTEREST_EXPENSE = "ZERO_INTEREST_EXPENSE"
    INVALID_INTEREST_SIGN = "INVALID_INTEREST_SIGN"

    # Warnings & Operational Notes
    NEGATIVE_EBIT_WARNING = "NEGATIVE_EBIT_WARNING"
    POINT_IN_TIME_DENOMINATOR_FALLBACK = "POINT_IN_TIME_DENOMINATOR_FALLBACK"
    CURRENCY_MISMATCH = "CURRENCY_MISMATCH"
    NON_REPORTED_EBITDA_RESTRICTION = "NON_REPORTED_EBITDA_RESTRICTION"

    # M7B.2 Advanced Diagnostics & Boundary Codes
    UNAVAILABLE_EFFECTIVE_TAX_RATE = "UNAVAILABLE_EFFECTIVE_TAX_RATE"
    NEGATIVE_OPERATING_PROFIT = "NEGATIVE_OPERATING_PROFIT"
    NON_POSITIVE_OPERATING_PROFIT = "NON_POSITIVE_OPERATING_PROFIT"
    NON_POSITIVE_INVESTED_CAPITAL = "NON_POSITIVE_INVESTED_CAPITAL"
    ZERO_PRETAX_INCOME = "ZERO_PRETAX_INCOME"
    ZERO_OPERATING_INCOME = "ZERO_OPERATING_INCOME"
    DISTORTED_PRETAX_EARNINGS = "DISTORTED_PRETAX_EARNINGS"
    DISTORTED_OPERATING_EARNINGS = "DISTORTED_OPERATING_EARNINGS"
    NON_POSITIVE_AVERAGE_ASSETS = "NON_POSITIVE_AVERAGE_ASSETS"
    NON_POSITIVE_AVERAGE_EQUITY = "NON_POSITIVE_AVERAGE_EQUITY"
    NON_POSITIVE_REVENUE = "NON_POSITIVE_REVENUE"
    NON_POSITIVE_BASE_REVENUE = "NON_POSITIVE_BASE_REVENUE"
    NON_POSITIVE_BASE_ASSETS = "NON_POSITIVE_BASE_ASSETS"
    NON_POSITIVE_EBIT = "NON_POSITIVE_EBIT"
    NON_POSITIVE_STARTING_VALUE = "NON_POSITIVE_STARTING_VALUE"
    INSUFFICIENT_CALENDAR_DAYS = "INSUFFICIENT_CALENDAR_DAYS"
    CFO_EBIT_DIVERGENCE_WARNING = "CFO_EBIT_DIVERGENCE_WARNING"
    SLOAN_ACCRUALS_WARNING = "SLOAN_ACCRUALS_WARNING"

    # M7B.3 Capital Allocation & Cash Flow Codes
    FCFF_RECONCILIATION_DIVERGENCE = "FCFF_RECONCILIATION_DIVERGENCE"
    FCFF_PROMOTED_CFO_FALLBACK = "FCFF_PROMOTED_CFO_FALLBACK"
    ACCRUAL_INTEREST_CFO_RECONCILIATION_NOTE = (
        "ACCRUAL_INTEREST_CFO_RECONCILIATION_NOTE"
    )
    NET_INTEREST_EXPENSE_FALLBACK = "NET_INTEREST_EXPENSE_FALLBACK"
    MISSING_DEPRECIATION_AMORTIZATION = "MISSING_DEPRECIATION_AMORTIZATION"
    NET_BORROWING_UNAVAILABLE = "NET_BORROWING_UNAVAILABLE"
    ZERO_NET_BORROWING_VERIFIED = "ZERO_NET_BORROWING_VERIFIED"
    PREFERRED_DIVIDEND_ABSENCE_UNVERIFIED = "PREFERRED_DIVIDEND_ABSENCE_UNVERIFIED"
    NEGATIVE_REINVESTMENT_OBSERVED = "NEGATIVE_REINVESTMENT_OBSERVED"
    HIGH_REINVESTMENT_WARNING = "HIGH_REINVESTMENT_WARNING"
    DISTORTED_FUNDAMENTAL_GROWTH = "DISTORTED_FUNDAMENTAL_GROWTH"
    NEGATIVE_FUNDAMENTAL_GROWTH = "NEGATIVE_FUNDAMENTAL_GROWTH"
    M_AND_A_DATA_UNAVAILABLE = "M_AND_A_DATA_UNAVAILABLE"
    NEGATIVE_OPERATING_NWC_NOTE = "NEGATIVE_OPERATING_NWC_NOTE"

    # M7B.3 EV & Capital Structure Codes
    MARKET_CAP_UNAVAILABLE = "MARKET_CAP_UNAVAILABLE"
    NON_POSITIVE_MARKET_CAP = "NON_POSITIVE_MARKET_CAP"
    NEGATIVE_ENTERPRISE_VALUE_WARNING = "NEGATIVE_ENTERPRISE_VALUE_WARNING"
    ZERO_OR_NEGATIVE_CAPITAL = "ZERO_OR_NEGATIVE_CAPITAL"
    PREFERRED_EQUITY_CONFIDENTLY_ABSENT = "PREFERRED_EQUITY_CONFIDENTLY_ABSENT"
    PREFERRED_EQUITY_INSUFFICIENTLY_DISCLOSED = (
        "PREFERRED_EQUITY_INSUFFICIENTLY_DISCLOSED"
    )
    MINORITY_INTEREST_CONFIDENTLY_ABSENT = "MINORITY_INTEREST_CONFIDENTLY_ABSENT"
    MINORITY_INTEREST_INSUFFICIENTLY_DISCLOSED = (
        "MINORITY_INTEREST_INSUFFICIENTLY_DISCLOSED"
    )

    # M7B.3 Credit & Distress Scoring Codes
    ZERO_LONG_TERM_DEBT_PASS_CONVENTION = "ZERO_LONG_TERM_DEBT_PASS_CONVENTION"
    UNCHANGED_POSITIVE_LEVERAGE_FAIL = "UNCHANGED_POSITIVE_LEVERAGE_FAIL"
    INSUFFICIENT_PIOTROSKI_SIGNALS = "INSUFFICIENT_PIOTROSKI_SIGNALS"
    PARTIAL_PIOTROSKI_SCORE_REPORTED = "PARTIAL_PIOTROSKI_SCORE_REPORTED"
    FINANCIAL_ENTITY_EXEMPTION = "FINANCIAL_ENTITY_EXEMPTION"
    ALTMAN_MODEL_DISPATCHED_SERVICE = "ALTMAN_MODEL_DISPATCHED_SERVICE"
    ALTMAN_MODEL_DISPATCHED_MANUFACTURING = "ALTMAN_MODEL_DISPATCHED_MANUFACTURING"
    ALTMAN_AMBIGUOUS_STRUCTURE_DISPATCH_SERVICE = (
        "ALTMAN_AMBIGUOUS_STRUCTURE_DISPATCH_SERVICE"
    )


class FundamentalMetricId(StrEnum):
    """
    Standardized identifiers for all canonical M7A & M7B fundamental metrics.
    """

    # --- Top-Line & Core Facts ---
    REVENUE = "REVENUE"
    COST_OF_REVENUE = "COST_OF_REVENUE"

    # --- Growth ---
    REVENUE_GROWTH_YOY = "REVENUE_GROWTH_YOY"
    REVENUE_GROWTH_QOQ = "REVENUE_GROWTH_QOQ"

    # --- Profitability ---
    GROSS_PROFIT = "GROSS_PROFIT"
    GROSS_PROFIT_MARGIN = "GROSS_PROFIT_MARGIN"
    OPERATING_INCOME = "OPERATING_INCOME"
    OPERATING_MARGIN = "OPERATING_MARGIN"
    NET_INCOME = "NET_INCOME"
    NET_PROFIT_MARGIN = "NET_PROFIT_MARGIN"
    RETURN_ON_ASSETS = "RETURN_ON_ASSETS"
    RETURN_ON_EQUITY = "RETURN_ON_EQUITY"
    EBITDA_MARGIN = "EBITDA_MARGIN"

    # --- Liquidity ---
    WORKING_CAPITAL = "WORKING_CAPITAL"
    CURRENT_RATIO = "CURRENT_RATIO"
    QUICK_RATIO = "QUICK_RATIO"
    CASH_RATIO = "CASH_RATIO"

    # --- Solvency ---
    GROSS_DEBT = "GROSS_DEBT"
    NET_DEBT = "NET_DEBT"
    DEBT_TO_EQUITY = "DEBT_TO_EQUITY"
    DEBT_TO_ASSETS = "DEBT_TO_ASSETS"
    INTEREST_COVERAGE = "INTEREST_COVERAGE"
    DEBT_TO_EBITDA = "DEBT_TO_EBITDA"
    NET_DEBT_TO_EBITDA = "NET_DEBT_TO_EBITDA"

    # --- Efficiency ---
    ASSET_TURNOVER = "ASSET_TURNOVER"
    RECEIVABLES_TURNOVER = "RECEIVABLES_TURNOVER"
    INVENTORY_TURNOVER = "INVENTORY_TURNOVER"
    PAYABLES_TURNOVER = "PAYABLES_TURNOVER"
    DAYS_SALES_OUTSTANDING = "DAYS_SALES_OUTSTANDING"
    DAYS_INVENTORY_OUTSTANDING = "DAYS_INVENTORY_OUTSTANDING"
    DAYS_PAYABLE_OUTSTANDING = "DAYS_PAYABLE_OUTSTANDING"
    CASH_CONVERSION_CYCLE = "CASH_CONVERSION_CYCLE"

    # --- Cash Flow ---
    OPERATING_CASH_FLOW = "OPERATING_CASH_FLOW"
    CAPITAL_EXPENDITURES = "CAPITAL_EXPENDITURES"
    FREE_CASH_FLOW = "FREE_CASH_FLOW"
    FCF_MARGIN = "FCF_MARGIN"
    FCF_CONVERSION = "FCF_CONVERSION"
    CFO_TO_NET_INCOME = "CFO_TO_NET_INCOME"
    FCF_TO_NET_INCOME = "FCF_TO_NET_INCOME"

    # --- M7B.2 Advanced Metrics ---
    EFFECTIVE_TAX_RATE = "EFFECTIVE_TAX_RATE"
    NOPAT = "NOPAT"
    INVESTED_CAPITAL = "INVESTED_CAPITAL"
    ROIC = "ROIC"
    TAX_BURDEN = "TAX_BURDEN"
    INTEREST_BURDEN = "INTEREST_BURDEN"
    EBIT_MARGIN = "EBIT_MARGIN"
    EQUITY_MULTIPLIER = "EQUITY_MULTIPLIER"
    DUPONT_ROE_3STEP = "DUPONT_ROE_3STEP"
    DUPONT_ROE_5STEP = "DUPONT_ROE_5STEP"
    SLOAN_ACCRUALS = "SLOAN_ACCRUALS"
    OPERATING_QUALITY_RATIO = "OPERATING_QUALITY_RATIO"
    CAGR = "CAGR"

    # --- M7B.3 Capital Allocation & Cash Flow ---
    DIVIDENDS_PAID = "DIVIDENDS_PAID"
    STOCK_REPURCHASES = "STOCK_REPURCHASES"
    STOCK_ISSUANCES = "STOCK_ISSUANCES"
    DEBT_ISSUED = "DEBT_ISSUED"
    DEBT_REPAID = "DEBT_REPAID"
    NET_DEBT_ISSUED = "NET_DEBT_ISSUED"
    M_AND_A_INVESTMENT = "M_AND_A_INVESTMENT"
    DIVIDEND_YIELD = "DIVIDEND_YIELD"
    BUYBACK_YIELD = "BUYBACK_YIELD"
    SHAREHOLDER_YIELD = "SHAREHOLDER_YIELD"
    NET_SHAREHOLDER_YIELD = "NET_SHAREHOLDER_YIELD"

    # --- M7B.3 Working Capital & Reinvestment ---
    OPERATING_CURRENT_ASSETS = "OPERATING_CURRENT_ASSETS"
    OPERATING_CURRENT_LIABILITIES = "OPERATING_CURRENT_LIABILITIES"
    OPERATING_NWC = "OPERATING_NWC"
    DELTA_NWC = "DELTA_NWC"
    REINVESTMENT = "REINVESTMENT"
    REINVESTMENT_RATE = "REINVESTMENT_RATE"
    FUNDAMENTAL_GROWTH = "FUNDAMENTAL_GROWTH"

    # --- M7B.3 Free Cash Flow ---
    FCFF = "FCFF"
    FCFF_CFO = "FCFF_CFO"
    FCFE = "FCFE"

    # --- M7B.3 Enterprise Value & Capital Structure ---
    MARKET_CAPITALIZATION = "MARKET_CAPITALIZATION"
    ENTERPRISE_VALUE = "ENTERPRISE_VALUE"
    TOTAL_CAPITAL = "TOTAL_CAPITAL"
    WEIGHT_EQUITY = "WEIGHT_EQUITY"
    WEIGHT_DEBT = "WEIGHT_DEBT"
    WEIGHT_PREFERRED = "WEIGHT_PREFERRED"

    # --- M7B.3 Credit Diagnostics ---
    PIOTROSKI_F_SCORE = "PIOTROSKI_F_SCORE"
    ALTMAN_Z_SCORE = "ALTMAN_Z_SCORE"
